version: "3"
services:
  php:
    build:
      context: .
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/www/webprogramminglabs.arsgrunin.ru/html/:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini
      
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: trendyhall
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
    - "9001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql